name: Build and Lint

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # adjust to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint  # adjust to your linting script

    - name: Build
      run: npm run build  # adjust to your build script

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build  # adjust to the directory containing your build artifacts
